<a href="https://colab.research.google.com/github/baubyte/HerramientasDeSoftwareParaElAnalisisDeDatos/blob/main/Tema_5/Ejercicios/Semana_05_Practica_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Práctica 005

Relacionada a Pandas y expresiones regulares.

In [24]:
from bs4 import BeautifulSoup
import re
import requests
import os

def descarga_dataset(url:str, nombre_del_archivo: str):
  """ Descarga el archivo de normas legales. Utilizar esta función porque
      el archivo es demasiado grande y muestra una pantalla de acuerdo.

      Args:
        url (str): La URL del archivo en Google Drive.
        nombre_del_archivo (str): Contiene el nombre del archivo con el que se
          guardará en el disco rígido.
  """
  matches = re.findall(r'/file/d/([a-zA-Z0-9_-]+)', url)

  if matches:
    file_id = matches[0]
    print("File ID:", file_id)
    url_download = f"https://drive.google.com/uc?id={file_id}"
    try:
      response = requests.get(url=url_download)
      page = BeautifulSoup(response.content, "html.parser")
      url = f'"{page.find("form", id="download-form").get("action")}"'
    except Exception:
      url = url_download

    # Especificar el path de descarga
    path_descarga = f'/content/{nombre_del_archivo}'

    # Crear directorio si no existe
    os.makedirs(os.path.dirname(path_descarga), exist_ok=True)

    # Descargar el archivo en el path especificado
    !wget -X POST {url} -O {path_descarga}
  else:
    print("File ID not found")

# Ejercicio 01

Vamos a trabajar con un dataset del mundial.

Descargar el dataset [https://drive.google.com/uc?id=1030-7OVCpZZTSozZ6dPREfovyFkykt21](https://drive.google.com/uc?id=1030-7OVCpZZTSozZ6dPREfovyFkykt21)

Mostrar:

- Mostrar la cantidad de filas
- Mostrar la cantidad de columnas
- Mostrar la cantidad de celdas que posee el dataset
- Mostrar el nombre de las columnas

Detalle del dataset.

Header | Definition
---|---------
`season` | The season during which the match was played
`date` | The date of the match (YYYY-MM-DD)
`league_id` | A unique identifier for the league this match was played in
`league` | The name of the league this match was played in
`team1` | The home team's name
`team2` | The away team's name
`spi1` | The home team's overall SPI rating before the match
`spi2` | The away team's overall SPI rating before the match
`prob1` | The probability of the home team winning the match
`prob2` | The probability of the away team winning the match
`probtie` | The probability of match ending in a draw (if applicable)
`proj_score1` | The number of goals we expected the home team to score
`proj_score2` | The number of goals we expected the away team to score
`importance1` | The importance of the match for the home team (0-100)
`importance2` | The importance of the match for the away team (0-100)
`score1` | The number of goals scored by the home team
`score2` | The number of goals scored by the away team
`xg1` | The number of expected goals created by the home team
`xg2` | The number of expected goals created by the away team
`nsxg1` | The number of non-shot expected goals created by the home team
`nsxg2` | The number of non-shot expected goals created by the away team
`adj_score1` | The number of goals scored by the home team, adjusted for game state
`adj_score2` | The number of goals scored by the home team, adjusted for game state

In [25]:
from google.colab import drive, files
import pandas as pd
import numpy as np

drive.mount("/content/drive")
url_dataset = 'https://drive.google.com/file/d/1030-7OVCpZZTSozZ6dPREfovyFkykt21'
dir_dataset: str = 'drive/MyDrive/kaggle/datasets'
name_dataset = "wc_matches"
filename = f"{dir_dataset}/{name_dataset}/{name_dataset}.csv"
descarga_dataset(url_dataset, filename)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
File ID: 1030-7OVCpZZTSozZ6dPREfovyFkykt21
--2026-04-08 23:38:01--  https://drive.google.com/uc?id=1030-7OVCpZZTSozZ6dPREfovyFkykt21
Resolving drive.google.com (drive.google.com)... 142.251.8.101, 142.251.8.113, 142.251.8.100, ...
Connecting to drive.google.com (drive.google.com)|142.251.8.101|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1030-7OVCpZZTSozZ6dPREfovyFkykt21 [following]
--2026-04-08 23:38:02--  https://drive.usercontent.google.com/download?id=1030-7OVCpZZTSozZ6dPREfovyFkykt21
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 108.177.125.132, 2404:6800:4008:c01::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|108.177.125.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7905 (7.7K) [application/octet-stream]
Saving to: ‘/content/drive/MyDrive/kaggle/datasets/wc_matches/wc_matches.csv’

/content/drive/MyDr 100%[===================>]   7.72K  --.-KB/s    in 0.001s

2026-04-08 23:38:03 (14.7 MB/s) - ‘/content/drive/MyDrive/kaggle/datasets/wc_matches/wc_matches.csv’ saved [7905/7905]

In [27]:
df_wc_matches = pd.read_csv(filename)

print(f"Cantidad de filas: {df_wc_matches.shape[0]}")
print(f"Cantidad de columnas: {df_wc_matches.shape[1]}")
print(f"Cantidad de celdas: {df_wc_matches.size}")
print(f"Nombre de las columnas: {df_wc_matches.columns.tolist()}")
print("\nPrimeras 10 filas:")
display(df_wc_matches.head(10))

Cantidad de filas: 64
Cantidad de columnas: 20
Cantidad de celdas: 1280
Nombre de las columnas: ['date', 'league_id', 'league', 'team1', 'team2', 'spi1', 'spi2', 'prob1', 'prob2', 'probtie', 'proj_score1', 'proj_score2', 'score1', 'score2', 'xg1', 'xg2', 'nsxg1', 'nsxg2', 'adj_score1', 'adj_score2']

Primeras 10 filas:

,date,league_id,league,team1,team2,spi1,spi2,prob1,prob2,probtie,proj_score1,proj_score2,score1,score2,xg1,xg2,nsxg1,nsxg2,adj_score1,adj_score2
0,2022-11-20,1908,FIFA World Cup,Qatar,Ecuador,51.00,72.74,0.2369,0.5045,0.2586,1.13,1.75,0,2,0.23,1.14,0.24,1.35,0.00,2.10
1,2022-11-21,1908,FIFA World Cup,England,Iran,85.96,62.17,0.6274,0.1187,0.2539,1.70,0.58,6,2,1.04,1.45,1.50,0.32,5.78,2.10
2,2022-11-21,1908,FIFA World Cup,Senegal,Netherlands,73.84,86.01,0.2235,0.5053,0.2712,0.99,1.63,0,2,0.70,0.68,1.22,1.83,0.00,1.58
3,2022-11-21,1908,FIFA World Cup,USA,Wales,74.83,65.58,0.4489,0.2591,0.2920,1.42,1.01,1,1,0.33,1.78,0.48,0.95,1.05,1.05
4,2022-11-22,1908,FIFA World Cup,Argentina,Saudi Arabia,87.21,56.87,0.7228,0.0807,0.1966,2.11,0.54,1,2,1.63,0.15,2.40,0.53,1.05,2.10
5,2022-11-22,1908,FIFA World Cup,Denmark,Tunisia,80.02,65.85,0.5001,0.2054,0.2945,1.44,0.82,0,0,0.66,1.16,1.33,0.69,0.00,0.00
6,2022-11-22,1908,FIFA World Cup,Mexico,Poland,74.30,68.28,0.4238,0.2802,0.2960,1.37,1.06,0,0,0.45,1.02,1.19,0.49,0.00,0.00
7,2022-11-22,1908,FIFA World Cup,France,Australia,87.71,60.83,0.6921,0.1009,0.2070,2.09,0.65,4,1,3.03,0.26,3.01,0.30,4.18,1.05
8,2022-11-23,1908,FIFA World Cup,Morocco,Croatia,75.62,78.84,0.3176,0.3898,0.2926,1.18,1.34,0,0,0.28,0.88,0.54,0.64,0.00,0.00
9,2022-11-23,1908,FIFA World Cup,Germany,Japan,88.77,71.44,0.6041,0.1740,0.2219,2.14,1.06,1,2,3.10,1.20,3.10,0.85,1.05,2.10

# Ejercicio 02

Obtener todos los países de forma única que participaron del mundial de futbol. Mostrar los nombre ordenados.

In [41]:
countries =set();
df_group_teams1 = df_wc_matches.groupby('team1')
df_group_teams2 = df_wc_matches.groupby('team2')
countries.update(df_group_teams1.groups.keys())
countries.update(df_group_teams2.groups.keys())
print("Paises participantes:")
print(sorted(countries))

Paises participantes:
['Argentina', 'Australia', 'Belgium', 'Brazil', 'Cameroon', 'Canada', 'Costa Rica', 'Croatia', 'Denmark', 'Ecuador', 'England', 'France', 'Germany', 'Ghana', 'Iran', 'Japan', 'Mexico', 'Morocco', 'Netherlands', 'Poland', 'Portugal', 'Qatar', 'Saudi Arabia', 'Senegal', 'Serbia', 'South Korea', 'Spain', 'Switzerland', 'Tunisia', 'USA', 'Uruguay', 'Wales']

# Ejercicio 03

Obtener la mayor cantidad de goles en un partido que hizo cada selección. Mostrar El nombre del país de la selección y la cantidad de goles.

In [59]:
df_scores_team1 = df_wc_matches.groupby('team1').aggregate({'score1': 'max'}).rename(columns={'score1': 'max_score'})
df_scores_team2 = df_wc_matches.groupby('team2').aggregate({'score2': 'max'}).rename(columns={'score2': 'max_score'})
df_scores_teams_concat = pd.concat([df_scores_team1, df_scores_team2])
df_teams_scores = df_scores_teams_concat.groupby(df_scores_teams_concat.index)['max_score'].max()
df_teams_scores = df_teams_scores.reset_index()
df_teams_scores.columns = ['team', 'max_goals']
print("Paises con mayor cantidad de goles:")
display(df_teams_scores.sort_values(by='max_goals', ascending=False))

Paises con mayor cantidad de goles:

            team  max_goals
26         Spain          7
10       England          6
20      Portugal          6
3         Brazil          4
12       Germany          4
7        Croatia          4
11        France          4
13         Ghana          3
18   Netherlands          3
23       Senegal          3
27   Switzerland          3
24        Serbia          3
4       Cameroon          3
0      Argentina          3
14          Iran          2
9        Ecuador          2
30       Uruguay          2
22  Saudi Arabia          2
17       Morocco          2
25   South Korea          2
6     Costa Rica          2
15         Japan          2
19        Poland          2
16        Mexico          2
8        Denmark          1
1      Australia          1
2        Belgium          1
5         Canada          1
21         Qatar          1
28       Tunisia          1
29           USA          1
31         Wales          1

Para obtener la mayor cantidad de goles por selección, podemos combinar los DataFrames `df_scores_team1` y `df_scores_team2` de manera que se considere el máximo de ambos roles (equipo local o visitante).  

1. Renombramos las columnas de puntuación a un nombre común (ej. `max_score`).  
2. Concatenamos los DataFrames.  
3. Agrupamos por el nombre del equipo y tomamos el máximo valor de `max_score`.

# Ejercicio 04

Graficar el DataFrame del ejercicio 03 como un gráfico de barras.

# Ejercicio 05

Levantar el siguiente dataset de kaggle `stephenknoth/spanish-language-articles` en un DataFrame donde cada fila sea un texto/archivo.

`El directorio tiene varios archivos.`

`Los archivos deberían dar un error al leerlos, ver el tema de encoding.`

# Ejercicio 06

Tomar el DataFrame del ejercicio anterior y crear las siguientes columnas:
- Fecha: debe ir un True si el texto posee una fecha
- Email: debe ir en True si contiene algún email.
- Teléfono: debe ir en True si contiene algún teléfono. Vamos a suponer celulares de argentina.
- Tarjeta de crédito: debe ir en True si contiene algúna tarjeta de crédito.