<a href="https://colab.research.google.com/github/baubyte/HerramientasDeSoftwareParaElAnalisisDeDatos/blob/main/Tema_6/Ejercicios/Semana_06_Practica_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 006

Relacionada a nltk, spacy y textstat.

# Ejercicio 01

Descargar el dataset `kevinmorgado/spanish-news-classificatio` desde kaggle, levantarlo con pandas.

Con este dataset ya trabajamos en la práctica 4.

In [1]:
!pip install kaggle tabulate

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.1)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (0.9.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.17 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.18)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.2.25)

In [18]:
!python -m spacy download es_core_news_sm

Collecting es-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.8.0/es_core_news_sm-3.8.0-py3-none-any.whl (12.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 40.2 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('es_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [19]:
import os
import pandas as pd
from google.colab import userdata, drive, files
import re
from tabulate import tabulate
import nltk
from nltk.corpus import stopwords
import spacy
from nltk.stem import SnowballStemmer

In [4]:
#1. Montar Drive
drive.mount("/content/drive")

# 2. Extraemos las credenciales de forma segura desde los Secrets de Colab
os.environ["KAGGLE_USERNAME"] = userdata.get('KAGGLE_USERNAME')
os.environ["KAGGLE_KEY"] = userdata.get('KAGGLE_KEY')
#3. Direcorios y datasets
dir_dataset: str = '/content/drive/MyDrive/kaggle/datasets'

spanish_news_classificatio_path = os.path.join(dir_dataset,'spanish-news-classification', "df_total.csv")
df_spanish_news_classificatio = pd.read_csv(spanish_news_classificatio_path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Ejercicio 02

Al dataset anterior agregarle una nueva columna llamada `nltk_sin_stopword` quitando los stop words de la columna `news`según nltk.

In [13]:
nltk.download('stopwords')
spanish_stopwords = set(stopwords.words('spanish'))

def remove_nltk_stopwords(text):
    if isinstance(text, str):
        words = re.findall(r'\b\w+\b', text.lower())
        filtered_words = [word for word in words if word not in spanish_stopwords]
        return ' '.join(filtered_words)
    return text

df_spanish_news_classificatio['nltk_sin_stopword'] = [
    remove_nltk_stopwords(text) for text in df_spanish_news_classificatio['news'].values
]

display(df_spanish_news_classificatio[['news', 'nltk_sin_stopword']].head())

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,news,nltk_sin_stopword
0,Durante el foro La banca articulador empresari...,foro banca articulador empresarial desarrollo ...
1,El regulador de valores de China dijo el domin...,regulador valores china dijo domingo buscará c...
2,En una industria históricamente masculina como...,industria históricamente masculina aviación vi...
3,Con el dato de marzo el IPC interanual encaden...,dato marzo ipc interanual encadena decimoquint...
4,Ayer en Cartagena se dio inicio a la versión n...,ayer cartagena dio inicio versión número 56 co...

# Ejercicio 03

Al dataset anterior agregarle una nueva columna llamada `nltk_stemn_sin_stopword` cambiando las palabras de la columna `nltk_sin_stopword` por su stem según nltk.

In [15]:
spanish_stemmer = SnowballStemmer('spanish')

def stem_text(text):
    if isinstance(text, str):
        words = re.findall(r'\b\w+\b', text.lower())
        stemmed_words = [spanish_stemmer.stem(word) for word in words]
        return ' '.join(stemmed_words)
    return text

df_spanish_news_classificatio['nltk_stemn_sin_stopword'] = [
    stem_text(text) for text in df_spanish_news_classificatio['nltk_sin_stopword'].values
]

# Mostrar el resultado
display(df_spanish_news_classificatio[['nltk_sin_stopword', 'nltk_stemn_sin_stopword']].head())

,nltk_sin_stopword,nltk_stemn_sin_stopword
0,foro banca articulador empresarial desarrollo ...,for banc articul empresarial desarroll sosten ...
1,regulador valores china dijo domingo buscará c...,regul valor chin dij doming busc cooper estrec...
2,industria históricamente masculina aviación vi...,industri histor masculin aviacion viv present ...
3,dato marzo ipc interanual encadena decimoquint...,dat marz ipc interanual encaden decimoquint ta...
4,ayer cartagena dio inicio versión número 56 co...,ayer cartagen dio inici version numer 56 conve...

# Ejercicio 04

Al dataset anterior agregarle una nueva columna llamada `spacy_sin_stopword` quitando los stop words de la columna `news` según spacy.

In [23]:
nlp_es_sm = spacy.load('es_core_news_sm')

def remove_spacy_stopwords(text):
    if isinstance(text, str):
        doc = nlp_es_sm(text.lower())
        filtered_words = [token.text for token in doc if not token.is_stop and not token.is_punct and not token.is_space]
        return ' '.join(filtered_words)
    return text

df_spanish_news_classificatio['spacy_sin_stopword'] = [
    remove_spacy_stopwords(text) for text in df_spanish_news_classificatio['news'].values
]

# Mostrar el resultado
display(df_spanish_news_classificatio[['news', 'spacy_sin_stopword']].head())

,news,spacy_sin_stopword
0,Durante el foro La banca articulador empresari...,durante el foro la banca articulador empresari...
1,El regulador de valores de China dijo el domin...,el regulador de valores de china dijo el domin...
2,En una industria históricamente masculina como...,en una industria históricamente masculina como...
3,Con el dato de marzo el IPC interanual encaden...,con el dato de marzo el ipc interanual encaden...
4,Ayer en Cartagena se dio inicio a la versión n...,ayer en cartagena se dio inicio a la versión n...

# Ejercicio 05

Al dataset anterior agregarle una nueva columna llamada `spacy_lemma_sin_stopword` cambiando las palabras de la columna `spacy_sin_stopword` por su lemma según spacy.

In [ ]:
nlp_es_sm = spacy.load('es_core_news_sm')

def lemmatize_spacy_text(text):
    if isinstance(text, str):
        doc = nlp_es_sm(text)
        lemmas = [token.lemma_ for token in doc]
        return ' '.join(lemmas)
    return text

df_spanish_news_classificatio['spacy_lemma_sin_stopword'] = [
    lemmatize_spacy_text(text) for text in df_spanish_news_classificatio['spacy_sin_stopword'].values
]

display(df_spanish_news_classificatio[['spacy_sin_stopword', 'spacy_lemma_sin_stopword']].head())

# Ejercicio 06

Estimar y agregar como columnas el tiempo de lectura de las columnas :

- news (rt_news)
- nltk_sin_stopword (rt_nltk_sin_stopword)
- nltk_stemn_sin_stopword (rt_nltk_stemn_sin_stopword)
- spacy_sin_stopword (rt_spacy_sin_stopword)
- spacy_lemma_sin_stopword (rt_spacy_lemma_sin_stopword)

# Ejercicio 07

Calcular y agregar como columnas el indice de perspicuidad de Szigriszt-Pazos para las columnas:

- news (isp_news)
- nltk_sin_stopword (isp_nltk_sin_stopword)
- nltk_stemn_sin_stopword (isp_nltk_stemn_sin_stopword)
- spacy_sin_stopword (isp_spacy_sin_stopword)
- spacy_lemma_sin_stopword (isp_spacy_lemma_sin_stopword)

# Ejercicio 08

Analizar las columnas creadas.

Escribir alguna conclusión simple de no mas de 10 renglones.